/*
Object orient langauge is model to writet programme

Encaptualization :it will encaputalize data in class. if a declare one place also another classes. It will not class or overwritten
Abstaction: Only show what is required and hide what is not required. It will show only result. It will show the         how we got the result
Inheritan ce = it will inherit property from parent
Polimorphism = it means based on userinput it will show result according. Customer care is best exampel







*/
